# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example3.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xample3.proto\"\xa5\x01\n\x07\x45xample\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x11\n\tbbox_left\x18\x05 \x01(\x05\x12\x10\n\x08\x62\x62ox_top\x18\x06 \x01(\x05\x12\x12\n\nbbox_width\x18\x07 \x01(\x05\x12\x13\n\x0b\x62\x62ox_height\x18\x08 \x01(\x05\x12\x0e\n\x06\x64igits\x18\t \x03(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example3_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXAMPLE._serialized_start=19
  _EXAMPLE._serialized_end=184
# @@protoc_insertion_point(module_scope)
